In [89]:
import pandas as pd
import numpy as np
import yfinance as yf
import requests

df_planilha_acoes = pd.read_csv("planilha_acoes_2.csv", low_memory=False, encoding='latin1') # Carregando a planilha
display(df_planilha_acoes)

    AÃÃO  QTD    PM  PREÃO
0    SAPR3   10    19     NaN
1    ITUB3   20  5,76     NaN
2    ITSA4   30    22     NaN
3    WEGE3   40    27     NaN
4   TAEE11   10    34     NaN
5    CMIG4   10    10     NaN
6    BBSE3   10    10     NaN
7    LEVE3   10    10     NaN
8    CMIN3   10    10     NaN
9    CSMG3   10    10     NaN
10   CPLE3   10    10     NaN
11   BBAS3   10    10     NaN
12   SAPR4   10    10     NaN
13   PETR4   10    10     NaN

In [90]:
######################## TRATANDO PLANILHA
df_planilha_acoes = df_planilha_acoes.rename(columns={'AÃÃO': 'AÇÃO'})
df_planilha_acoes = df_planilha_acoes.rename(columns={'PREÃO': 'PREÇO'})
df_planilha_acoes['AÇÃO'] = df_planilha_acoes['AÇÃO'].str.upper().str.strip().str.replace(' ','') # Padroniza o ticker para o padrão
df_planilha_acoes['PM'] = df_planilha_acoes['PM'].str.replace(',','.') 
df_planilha_acoes['PM'] = df_planilha_acoes['PM'].astype(float)        # Transforma o valor que estava sendo lido como string para float

############# TRATANDO OS INPUTS PARA USAR NA FUNÇÃO
ativos = df_planilha_acoes['AÇÃO'].tolist()
lista_ativos_renomeados =[]
for ativo in ativos:
    posicao = ativo.find('3')
    if posicao ==-1:
        posicao = ativo.find('4')
        if posicao ==-1:
            posicao = ativo.find('6')
            if posicao ==-1:
                    posicao = ativo.find('11')
    ativo = ativo+'.SA'
    lista_ativos_renomeados.append(ativo)

########################## GERANDO A PLANILHA
df_precos_fechamento = yf.download(lista_ativos_renomeados, period="1d")
df_precos_fechamento = df_precos_fechamento['Close']
display(df_precos_fechamento)

[*********************100%***********************]  14 of 14 completed

Ticker,BBAS3.SA,BBSE3.SA,CMIG4.SA,CMIN3.SA,CPLE3.SA,CSMG3.SA,ITSA4.SA,ITUB3.SA,LEVE3.SA,PETR4.SA,SAPR3.SA,SAPR4.SA,TAEE11.SA,WEGE3.SA
Date,,,,,,,,,,,,,,
2026-04-24,22.700001,34.290001,13.05,4.74,16.59,57.32,14.22,44.32,36.200001,47.16,10.08,8.41,44.110001,47.799999

In [91]:
#################### ATUALIZANDO OS PREÇOS
lista_valores = []
for ativo in lista_ativos_renomeados:
    valor = float(df_precos_fechamento[ativo].iloc[0])
    lista_valores.append(valor)
df_planilha_acoes['PREÇO'] = lista_valores
df_planilha_acoes['PREÇO'] = df_planilha_acoes['PREÇO'].round(2)
display(df_planilha_acoes)
df_planilha_acoes.to_csv('planilha_acoes2.csv')

      AÇÃO  QTD     PM  PREÇO
0    SAPR3   10  19.00  10.08
1    ITUB3   20   5.76  44.32
2    ITSA4   30  22.00  14.22
3    WEGE3   40  27.00  47.80
4   TAEE11   10  34.00  44.11
5    CMIG4   10  10.00  13.05
6    BBSE3   10  10.00  34.29
7    LEVE3   10  10.00  36.20
8    CMIN3   10  10.00   4.74
9    CSMG3   10  10.00  57.32
10   CPLE3   10  10.00  16.59
11   BBAS3   10  10.00  22.70
12   SAPR4   10  10.00   8.41
13   PETR4   10  10.00  47.16