In [13]:
import pandas as pd
import numpy as np
df_previa = pd.read_csv("previa.csv", low_memory=False)
display(df_previa)

,nome,Segunda,Terça,Quarta,Quinta,Sexta,Sábado,Domingo
0,rafael_passos,"ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce"
1,pedro_nascimento,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a
2,julia_alvarenga,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a
3,rodrigo_barcelos,"ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce"
4,fernanda_dias,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a
5,felipe_juciv,"ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce"
6,rodolfo_belato,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a
7,virna_jandiroba,"ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce"
8,vinicius_bueno,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a
9,joao_fonseca,"ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce"
10,leticia_horiguchi,"ca,a,j,ce","ca,a,j,ce","ca,j,ce","ca,a,j,ce","ca,a,j,ce","ca,a,j,ce",a

In [10]:
#################### INÍCIO DO PROGRAMA ##############
dia = input(f'Qual dia deseja consultar? ')
refeicao = input(f'Qual refeição deseja consultar? ')
# Importante para armazenar quem já comeu, e posteriormente, criará a planilha de presença
presenca = [] 


#################    LOOP    #########################    
while True:
    nome = input('\nQual seu nome? ')
    if nome == 'fim': # Palavra-senha para finalizar o programa
        break

    # Checa se o nome está na prévia, se não estiver, o programa reinicia
    nome_na_previa = df_previa.loc[df_previa['nome'] == nome]
    if nome_na_previa.empty:
        print('Seu nome não está na prévia.')
        continue

    # Acessa a coluna 'Dia' na linha da variável nome
    # Serve para filtrar se a pessoa está com nome naquela refeição, naquele dia   
    refeicoes_dia_e_nome = df_previa.loc[df_previa['nome']== nome, dia].values[0]

    if refeicao in refeicoes_dia_e_nome:             # Verifica se ela está com nome nesta refeição ou não
        id_presenca = {'nome': nome, dia : refeicao} # Cria um dicionário para ser utilizado como dado
        # 1. Checa se a pessoa já comeu
        if id_presenca in presenca:
            print('Esse nome já foi utilizado para esta refeição!')
        # 2. Se não comeu, checa se está com nome na refeição e libera a entrada
        elif refeicao in refeicoes_dia_e_nome:
            print('Está com nome, pode entrar!')
            presenca.append(id_presenca) # Adiciona o dicionário la lista presenca para ser utilizado como conferência
         # 3. Se não comeu e não está na lista, não está com nome nesta refeição
    else:
        print('Você está sem nome nesta refeição!') 
 ########### Cria planilha de quem comeu (df_presenca) ##############
df_presenca = pd.DataFrame(presenca)
print('Conferência finalizada!')

Está com nome, pode entrar!
Está com nome, pode entrar!
Você está sem nome nesta refeição!
Conferência finalizada!

In [11]:
# Cria a planilha de quem tem o nome nestá refeição, modificando conforme necessário
df_conferencia = df_previa[['nome', dia]].copy()
df_conferencia[dia] = np.where(df_conferencia[dia].str.contains(refeicao, na=False), refeicao, 'Não está')
condicao = df_conferencia[dia]== refeicao
df_conferencia = df_conferencia[(condicao)]

# Subtraindo os dados de uma planilha com outra, cria a planilha de quem faltou
df_faltosos = df_conferencia[~df_conferencia['nome'].isin(df_presenca['nome'])]

############### EXIBIÇÃO DAS PLANILHAS ######################
print(f'Essa planilha é de quem esta com nome no(a) {refeicao} de {dia}.')
display(df_conferencia)
print(f'Essa planilha é de quem compareceu no(a) {refeicao} de {dia}.')
display(df_presenca)
print(f'Essa planilha é de quem faltou no(a) {refeicao} de {dia}.')
display(df_faltosos)

Essa planilha é de quem esta com nome no(a) j de Domingo.

               nome Domingo
0     rafael_passos       j
3  rodrigo_barcelos       j
5      felipe_juciv       j
7   virna_jandiroba       j
9      joao_fonseca       j

Essa planilha é de quem compareceu no(a) j de Domingo.

           nome Domingo
0  felipe_juciv       j
1  joao_fonseca       j

Essa planilha é de quem faltou no(a) j de Domingo.

               nome Domingo
0     rafael_passos       j
3  rodrigo_barcelos       j
7   virna_jandiroba       j